name: acromedia-commerce-demo
recipe: drupal8
config:
  webroot: web
services:
  localhost:
    type: solr:5.5
    portforward: true
    core: drupalcommerce_demo
    config:
      dir: web/modules/contrib/search_api_solr/solr-conf/5.x

