version: "2"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes_from:
      - container:mysql_data
    volumes:
      - .:/var/www/html

  php:
    image: ${PHP_IMAGE}
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      DB_HOST: mysql
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: ${DB_NAME}
      DB_DRIVER: mysql
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  nginx:
    image: git.acromedia.com:4567/acro/docker/acro-drupal:nginx
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/${DOC_ROOT}
    depends_on:
      - php
    volumes_from:
      - php
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${SITE_NAME}.docker.localhost"

  solr:
    image: solr:5
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.drupal.docker.localhost'
    volumes_from:
      - container:solr_data
    volumes:
      - .:/var/www/html

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  memcached:
    image: memcached:1.4-alpine

  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.drupal.docker.localhost'

  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
